Update github.com/chromedp/chromedp in the root go.mod to v0.9.5
Update the dependency github.com/chromedp/chromedp to v0.9.5 from
v0.9.3 in the root of the github.com/vugu/vugu module.

This is required to connect to the latest (as of 19th July 2024) version
of the chromedp container without generating the error:

ERROR: could not unmarshal event: parse error: expected string near offset 583 of 'cookiePart...'

in each of the wasm test suite tests.

Update dependencies of github.com/chromedp/chromedp v0.9.5 in wasm test suite

Upgrading github.com/chromedp/chromedp to v0.9.5 from v0.9.3 upgrades
the following dependancies of github.com/chromedp/chromedp

Upgrade:

github.com/chromedp/cdproto v0.0.0-20240202021202-6d0b6a386732 // indirect
to
github.com/chromedp/cdproto v0.0.0-20240709201219-e202069cc16b // indirect

github.com/gobwas/ws v1.3.2 // indirect
to
github.com/gobwas/ws v1.4.0 // indirect

golang.org/x/sys v0.19.0 // indirect
to
golang.org/x/sys v0.22.0 // indirect
        gopkg.in/yaml.v3 v3.0.1 // indirect

This upgrade has been applied to all of the go.mod's and go.sum's in the
wasm-test-suite